### ISSUE TITLE
Docker logs empty after recreating simplexmq container

### ISSUE THREAD

**Issue by mrg358** [simplex-chat/simplexmq#638] opened 2023-02-15 19:59 UTC
After recreating `simplexmq` container, docker no longer outputs `smp-server.log` content.

**Comment by shumvgolove** [comment] 2023-02-16 06:38
Please specify exact steps to reproduce the issue.

**Comment by mrg358** [comment] 2023-02-16 14:12
Sure. I tried to reproduce again fresh. Same results.

Step 1.
```
docker run -d -e addr="smp1.example.net" -p 5223:5223 -v $HOME/simplex/config:/etc/opt/simplex:z -v $HOME/simplex/logs:/var/opt/simplex:z --name simplexmq simplexchat/simplexmq
```
```
--name simplexmq simplexchat/simplexmq
0aa8c59aac27456c14bbd5f24c80e8ab667306f0779dfbc1d24a3aabcdef455b
```
Step 2.
```
docker logs -f simplexmq
```

```
Signature ok
subject=CN = smp1.example.net
Getting CA Private Key
Server initialized, you can modify configuration in /etc/opt/simplex/smp-server.ini.
Run `smp-server start` to start server.
----------
You should store CA private key securely and delete it from the server.
If server TLS credential is compromised this key can be used to sign a new one, keeping the same server identity and established connections.
CA private key location:
/etc/opt/simplex/ca.key
----------
SMP server v4.3.1
Fingerprint: IJzSOqjnrF-dsybOHO0DVSRY3oXq5abFZ3M347htB5g=
Server address: smp://IJzSOqjnrF-dsybOHO0DVSRY3oXq5abFZ3M347htB5g=@smp1.example.net
```
Step 3.
```
docker stop simplexmq && docker rm simplexmq
```
Step 4.
```
docker run -d -e addr="smp1.example.net" -p 5223:5223 -v $HOME/simplex/config:/etc/opt/simplex:z -v $HOME/simplex/logs:/var/opt/simplex:z --name simplexmq simplexchat/simplexmq
```
```
--name simplexmq simplexchat/simplexmq
31c5d07de2b307ac011b1c9ab5f473194b0e6cb17ac486e06e51440e546e837a
```
Step 5.
```
docker logs -f simplexmq
```
```
 
``` 
docker logs empty, no status. 

Step 6.
```
sudo tail -f /home/ubuntu/simplex/logs/smp-server.log
```
```
SMP server v4.3.1
Fingerprint: IJzSOqjnrF-dsybOHO0DVSRY3oXq5abFZ3M347htB5g=
Server address: smp://IJzSOqjnrF-dsybOHO0DVSRY3oXq5abFZ3M347htB5g=@smp1.example.net
Store log: /var/opt/simplex/smp-server-store.log
Listening on port 5223 (TLS)...
not expiring inactive clients
creating new queues allowed
[INFO 2023-02-16 14:00:45 +0000 src/Simplex/Messaging/Server.hs:739] restoring messages from file /var/opt/simplex/smp-server-messages.log
[INFO 2023-02-16 14:00:45 +0000 src/Simplex/Messaging/Server.hs:749] messages restored
```

i can confirm simplexmq runs and functions ok, but docker fails to output `smp-server.log` file after container re-creation.

**Comment by samsapti** [comment] 2023-04-22 19:37
@mrg358 the reason there's no output in `docker logs`, is probably due to the last line in `entrypoint`:

```bash
exec smp-server start > "$logd"/smp-server.log 2>&1
```

It redirects all output to `smp-serverlog` instead of `stdout`/`stderr`. Now, the reason it's printed the first time SimpleXMQ is run, is due to line 19 in `entrypoint`:

```
smp-server init -y -l "$@"
```

This is the first time initialization of the SMP server (hence it only outputs info on first run), notice that the output is not redirected to a file, so it prints to `stdout`/`stderr`, which is why it's catched by `docker logs`.

**Comment by shumvgolove** [comment] 2023-04-23 12:15
Hey @samsapti

Yeah, you're right. Since `docker logs` is the proper way to log (duh) output, I'll remove the redirection to the file in the `entrypoint`. Thanks for investigating.

**Comment by shumvgolove** [comment] 2023-04-26 08:29
Should be fixed with https://github.com/simplex-chat/simplexmq/commit/605970f6b6e4109c9d6f38758b57e7e112fa48c0 . Please pull recent image from [simplexchat/smp-server](https://hub.docker.com/r/simplexchat/smp-server).

**Closed by shumvgolove** 2023-04-26 08:29 UTC
